HPRC/Dominet

client.py, game.py, reactionHandler.py, sets/hinterlands.py, sets/intrigue.py, static/js/services/client.js, tests/hinterlands_tests.py
also fixing some print statements and update mode to be smarter (ends turn when updating mode if no buys left and was buy mode)
=> implement Mandarin

client.py, sets/base.py, sets/card.py, sets/hinterlands.py, sets/intrigue.py, sets/prosperity.py, tests/hinterlands_tests.py
added announce_self method and change onbuy/ongain to be unbound attributes.
=> Nomad camp + Duchess

sets/base.py, sets/card.py, sets/intrigue.py
- fix plural messages for 
- Ironworkss -> Ironworks
- Spys -> Spies
- Changed discard down msg to more clearly state to choose cards to discard.
=> Copy changes

client.py, db/users.py, game.py, net.py, sets/base.py, sets/prosperity.py, static/js/controllers/clientController.js, static/js/controllers/handController.js, static/js/controllers/supplyController.js, static/js/services/client.js, static/partials/game.html, tests/base_tests.py, tests/waiter_tests.py, username.html, waitHandler.py
- created afk timer to allow users to force forfeit if a player is taking too long #90 
- created tests for waiter for afk timer
- removed d/c timer as afk timer serves the same purpose
- also includes some bug fixes (Throne room chaining bug)
=> Implement afk timer 

client.py, net.py
- use traceback object to log exception for coroutines in on_message
- provides stack trace finally
=> better error log msgs YAY

sets/hinterlands.py, sets/supply.py, tests/hinterlands_tests.py
=> Implemented Silk Road and Highway

cardpile.py, reactionHandler.py, sets/base.py, sets/hinterlands.py, sets/intrigue.py, sets/prosperity.py, tests/base_tests.py, waitHandler.py
Refactor reactionhandler to be attribute of hand, fixing #79
=> Fix nested reaction bug

client.py, game.py
fixes buy phase initialization getting called multiple times per turn
- fixes peddler being the wrong price sometimes
=> added phase property to client

client.py, sets/card.py, sets/hinterlands.py, tests/hinterlands_tests.py
=> implement scheme, cleanup called once for each card class

sets/card.py, sets/hinterlands.py, sets/intrigue.py, sets/prosperity.py, tests/hinterlands_tests.py
* Implemenation of Cartographer
* few minor copy changes
=> Cartographer

sets/intrigue.py, tests/intrigue_tests.py
fix bug with player 3 stuck on waiting after player2 has finished choosing for torturer
=> update mode if player is not waiting after torturer

cardpile.py, client.py, sets/base.py, sets/hinterlands.py, sets/intrigue.py, sets/prosperity.py, static/js/controllers/supplyController.js, tests/hinterlands_tests.py
Implement Haggler, stables, oracle, noble brigand cards
select_from_supply now takes a constraint function to filter available cards to select from
=> Haggler, Stables, Oracle, Noble Brigand

sets/intrigue.py
fix saboteur interaction with price reduction causing deadlock
=> fix price reduction and saboteur bug

cardpile.py, sets/hinterlands.py, tests/hinterlands_tests.py
resolves #71 
also includes fix for oracle not drawing cards for player
=> Fix oracle bug, implement inn

sets/seaside.py, tests/seaside_tests.py
implemented caravan with unit tests
=> implemented caravan

client.py, sets/seaside.py, tests/seaside_tests.py
=> Merchant Ship and Treasure Map

sets/base.py, sets/hinterlands.py, sets/intrigue.py
=> override get_next for oracle

sets/intrigue.py, tests/intrigue_tests.py
=> fix saboteur not waiting for on_gains to resolve

net.py
prevent starting game if someone has left caused by race condition between leave table and start game.
=> check if table is full before starting game

sets/base.py, sets/hinterlands.py, sets/intrigue.py, sets/prosperity.py
=> adjust card descriptions and logs

client.py, static/js/controllers/supplyController.js, tests/game_tests.py, tests/hinterlands_tests.py, tests/prosperity_tests.py
=> Add server verification

client.py, static/js/controllers/selectController.js, tests/intrigue_tests.py
input deque causing issues where a double selection could be saved for the next selection, fixed tests
=> remove input deque, remove extra wait causing extra alerts

tests/base_tests.py
update base tests to use mocks
=> Mock refactor tests

client.py, sets/base.py, sets/card.py, sets/prosperity.py, sets/seaside.py, tests/base_tests.py, tests/card_tests.py, tests/game_tests.py, tests/prosperity_tests.py
add duration_cbs deque, add test class for generic card functionality,
fix bug with throne room tactician, fix bug with kings court duration duplicating
king's courts
=> refactor durations

game.py, sets/hinterlands.py, tests/hinterlands_tests.py
=> fix trader bug counting empty piles after adding back to supply
